{% set version = "1.1-1.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nozzle.r1
  version: {{ version|replace("-", "_") }}

source:
  fn: Nozzle.R1_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/Nozzle.R1_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/Nozzle.R1/Nozzle.R1_{{ version }}.tar.gz
  sha256: 777e0fdada4a4d4c590885897a52beb91a5d5a1b8073c471448b3644d9715639

build:
  noarch: generic
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('Nozzle.R1')"  # [not win]
    - "\"%R%\" -e \"library('Nozzle.R1')\""  # [win]

about:
  home: http://github.com/parklab/nozzle, http://gdac.broadinstitute.org/nozzle
  license: LGPL-2.0-only
  summary: The Nozzle package provides an API to generate HTML reports with dynamic user interface elements based on JavaScript and CSS (Cascading Style Sheets). Nozzle was designed to facilitate summarization and rapid browsing of complex results in data analysis pipelines where multiple analyses are performed frequently
    on big data sets. The package can be applied to any project where user-friendly reports need to be created.
  license_family: LGPL

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2
extra:
  recipe-maintainers:
    - conda-forge/r
