travis:
  secure:
    BINSTAR_TOKEN: qXW5qFzsRLLzXGBv/IX57YduPqmDIjZKA8Vx+QrcgFDxgmGt64i7vgPAhwCxRgXtQ57eMp42N81PZkGzvQBldXLYtKvIBAa+BHW9A8MoI2kzVdjsUchrsu1Nw+zArvLr7wAnpM9UD81ptd4UOoKR1u8+0dfGjvLlGYsKBhLovIVeTMSQPknjnAB1+5jqiBafxzgwWm46DjzBtN+mOYWYczJybx2cLSX3HeS5nf8tPMrWUcPIQoG3nIH/WWm1p/jU6g6uLHJbwTpSE/XKa+ICvWWS3uS2qNyujoou+Tj7USf8urwCCHcBprCfqRmdENGOytrVMQ2gwXLuVrMGUUvYhBORFZxyixEOvQDvbya81GS56KPk6+UMvn/740l05Kr2qoMNwzPBnD8HZGSUK9PDfg4EKuUfftAYpkA4kpL5IJiavkJD7a0nvLDQNKDSSW4/YrYW5WEK9yo6m0hCsl2kNA+H2TwyVJHBIlbliYAJManJsv0d4BGU78OJW+jOyGCT+owf8uDgX+yN0pG+aWp9qTg4OVEHZcqLnhuYAXEwXAyealhsCMrDQ7GNE2MCM2S68xJvn6FZF8aEHqs7HKK/vAFkGYSgTND4OMdFpC5hemgsRya8zSS9Xhdl/WFd+3WYbckcAAlnNljp32vT5ty6K2H78Qgk0e4fmbDdf6x8hTk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
