appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: oLHgrXlkIFFNUBn763RWp5O8TrmGlYCT/gCWuFLzf42MYOtUhbp2j4YAQDSOHiXcvjlRyKspZ5jIKm0vlOUqINfeaj1KWiY+4bNoTemboCbDFhqybjxqrCpXsRPGxRQ7K2Y+EiRZy37wsPErqdEGSf7vQrymujl67/43LzFuJqppcx+kVgDyzJxyNIR2mGj58xpq2jjZrz+Ni3ELX0Bw0q0V53c32Q9CMpfQTdQ6B/XbO9dd+GUbl5c6p/bEDyi3wUEVhePNz9HHnE9RAOWu/386BfThfGD6bt5qCGqfBApSdSeErlygrRJxAhgn02c+80xJMV/59Yhg9NFQxoZhzSrD/CRPJ8M8v9eLu9L3oDVFNyF9Tu/MeVjQV45cGKaBLyEvsqV0Gc/uEUJrweJjlUmf+MeAF5baibAxzUGoo/qzxijkiP297tmLaWvws4lShG2K59mNv5IFhdjnKvee9piHLMHC8pqZBJRqh0km2VSQx1ByBRSMOKuYXe2T1FTMlgdENkYBg/8FP1KuhArZHulyEllLzKWzaiO8Tsao4U4OIdfFuTpFlK+F2FsgbIe5SXPC2hBsn6GV65efvaLl2ApLYWi5WOQvw4J9+jeW6pc9gMdoksRUbK8GmAEY1oH35rRPvwOCX5m//4srKH5yw8jZoCwSqnReFaSZFjthtOs=}
bot:
  automerge: true
